Section "InputClass"
    Identifier "Touchpad libinput"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
    Option "NaturalScrolling" "false"
    Option "DisableWhileTyping" "on"
EndSection
