#repository=https://void.voidlinux.com.br/voidlinux/current
#repository=https://void.voidlinux.com.br/voidlinux/extra
#repository=https://void.voidlinux.com.br/voidlinux/current/nonfree
#repository=https://void.voidlinux.com.br/voidlinux/current/multilib
#repository=https://void.voidlinux.com.br/voidlinux/current/multilib/nonfree
