# /etc/xbps.d/bestmatching.conf
#
# Enable package best matching (disabled by default). If enabled a package with
# the greatest version available in all repositories will be choosen, rather
# than on the first package matching the expression.
#
bestmatching=true
