# /etc/xbps.d/keepconf.conf
#
# The `keepconf` (disabled by default) keyword can be used to prevent
# xbps from overwriting unchanged configuration files. Changed configuration
# files are unaffected by this keyword and are preserved by default.
#
# If set to false, xbps will overwrite configuration files that have not been
# changed since installation with their new version (if available).
#
# If set to true, xbps will not overwrite configuration files that have not
# been changed since installation. Instead, the new version (if available) is
# saved next to the configuration file as <name>.new-<version>.
#
keepconf=true
