#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from Hard Disk" \
   --class harddisk \
   --class os {
   exit
}

menuentry "Windows Boot Manager" \
   --class windows \
   --class os {
    insmod part_gpt
    insmod fat
    insmod chain
    search --no-floppy --file --set=root /EFI/Microsoft/Boot/bootmgfw.efi
    chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

#menuentry "UEFI Firmware Settings" \
#   --class firmware \
#   --class efi {
#    fwsetup
#}

#menuentry "Memtest86+" \
#   --class memtest \
#   --class system {
#    insmod part_gpt
#    insmod part_msdos
#    insmod linux
#    search --no-floppy --file --set=root /boot/memtest86+.bin
#    linux16 /boot/memtest86+.bin
#}

menuentry "Restart Computer" \
   --class restart \
   --class system {
    reboot
}

menuentry "Shutdown Computer" \
   --class shutdown \
   --class system {
    halt
}

